name: Build y Compilación Local

on:
  push:
    branches: ["Q/A"]
  pull_request:
    branches: ["Q/A"]

jobs:
  build-local:
    runs-on: self-hosted 
    
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4
        
      - name: Instalar dependencias del Backend
        working-directory: ./backend
        run: npm install
        
      - name: Generar cliente de Prisma
        working-directory: ./backend
        run: npx prisma generate
        
      - name: Instalar dependencias del Frontend
        working-directory: ./frontend
        run: npm install
        
      - name: Compilar Frontend (Vite)
        working-directory: ./frontend
        run: npm run build
