name: Deploy Local (Docker)

on:
  workflow_run:
    workflows: [" Build y Compilación Local"] # Escucha al archivo anterior
    types:
      - completed
    branches:
      - "Q/A"

jobs:
  deploy-local:
    # Solo se ejecuta si el Build fue exitoso
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    runs-on: self-hosted 
    
    steps:
      - name: Descargar el código aprobado
        uses: actions/checkout@v4

      - name: Detener contenedores anteriores
        run: docker compose down
        
      - name: Construir y levantar nueva versión
        run: docker compose up -d --build
