name: Deploy Producción a Azure

on:
  push:
    branches: ["main"]

jobs:
  deploy-produccion:
    name: Despliegue en Servidor Azure
    runs-on: ubuntu-latest

    steps:
      - name: Conectar a Azure y Desplegar
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}        
          username: ${{ secrets.USERNAME }}    
          key: ${{ secrets.SSH_KEY }}      
          script: |
            # 1. Entramos a la carpeta del proyecto en el servidor
            cd /home/${{ secrets.USERNAME }}/ryd-u
            
            # 2. Descargamos la última versión de la rama main
            git pull origin main
            
            # 3. Reconstruimos y levantamos los contenedores
            docker compose down
            docker compose up -d --build
